#!/usr/bin/env python
from pandocfilters import SmallCaps, toJSONFilter, Str, RawInline

"""
Various text replacement macros.
"""

macro_sub = {
        '[ms]' : [SmallCaps([Str('ms')])],
        '[d1]' : [SmallCaps([Str('d1')])],
        '[mt]' : [Str('movement')],
        '[e1]' : [SmallCaps([Str('e1')])],
        '[nl]' : [RawInline('latex', '\\\\*'), RawInline('html', '<br>')],
        '[ma]' : [SmallCaps([Str('m.a.')])],
        '[sc]' : [RawInline('latex', '\\textsc{')],
        '[ec]' : [RawInline('latex', '}')],
        '[ba]' : [SmallCaps([Str('b.a.')])],
        '[lo]' : [Str('Libretto')],
        '[so]' : [Str('Score')],
        '[mp]' : [SmallCaps([Str('mss')])],
        '[eg]' : [SmallCaps([Str('eg')])],
        }


def parse(key, val, fmt, meta):
    if key == 'Str':
        if val[:4] in macro_sub.keys():
            return macro_sub[val[:4]] + [Str(val[4:])]

if __name__ == "__main__":
  toJSONFilter(parse)
