#!/usr/bin/env python
from pandocfilters import RawBlock, toJSONFilter

"""
Does annotation stuff. For use with edNotes.sty.
HORRIFICALLY FRAGILE HORRIFICALLY HACKY DO NOT USE
ONCE PANDOC IMPLEMENTS A PROPER METHOD FOR FILTERING
NOTES.
"""

def latexBlock(s):
    return RawBlock('latex', s)

def parse(key, val, fmt, meta):
    if fmt == 'latex' and key == 'Div':
        [[ident, classes, kvs], contents] = val
        if "afterpage" in classes:
            return ([latexBlock('\\afterpage{')] +
                    contents +
                    [latexBlock('}')])
        if "center" in classes:
            return ([latexBlock('\\begin{center}')] +
                    contents +
                    [latexBlock('\\end{center}')])

if __name__ == "__main__":
  toJSONFilter(parse)
