#!/usr/bin/env python
from pandocfilters import RawBlock, toJSONFilter

"""
Does annotation stuff. For use with edNotes.sty.
HORRIFICALLY FRAGILE HORRIFICALLY HACKY DO NOT USE
ONCE PANDOC IMPLEMENTS A PROPER METHOD FOR FILTERING
NOTES.
"""

def latexBlock(s):
    return RawBlock('latex', s)

def parse(key, val, fmt, meta):
    if fmt == 'latex' and key == 'BlockQuote':
        return ([latexBlock('\\begin{verse}\n' +
                            '\\begin{linenumbers}\n' +
                            '\\modulolinenumbers[2]\n' +
                            '\\firstlinenumber{1}')] +
                val +
                [latexBlock('\\end{linenumbers}\n\\end{verse}')])


if __name__ == "__main__":
  toJSONFilter(parse)
